export const EggLocations = [
  {
    id: 1,
    latitude: -80,
    longitude: 3,
    name: 'Riddle 1',
    address: "What rock group has four men that don't sing?",
    email: '???',
    phone: '???',
    match: false,
  },
  {
    id: 2,
    latitude: 43.8791,
    longitude: -103.4591,
    name: 'Riddle 2',
    address: 'NICE JOB KEEP GOING!',
    email: 'In what city was the first skyscraper built?',
    phone: '???',
    match: false,
  },
  {
    id: 3,
    latitude: 41.8781,
    longitude: -87.6298,
    name: 'Riddle 3',
    address: 'NICE JOB ALMOST THERE!',
    email: 'In what city were the 1996 Olymipcs held?',
    phone: '???',
    match: false,
  },
  {
    id: 4,
    latitude: 33.749,
    longitude: -84.388,
    name: 'Riddle 4',
    address: 'LAST ONE!!!',
    email: 'In what city was the oldest College in the USA founded?',
    phone: '???',
    match: false,
  },
  {
    id: 5,
    latitude: 42.377,
    longitude: -71.1167,
    name: 'You did it!!!',
    address: ' CLICK ME!!!',
    match: false,
  },
]
